spring:
  application:
    name: collection-boxes

  jackson:
    serialization:
      indent_output: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always

